#!/usr/bin/env python3
"""
g9_chandrop_stats.py
=====================
EXPERIMENT_PLAN_CHANDROP.md Phase 6 — paired Wilcoxon + Cohen's d (+ BCa on the
headline mean) for every new comparison generated by promoting channel-dropout
ResNet-SE (ResNet-SE+CD) to the deep model of record. Mirrors the g1/g3/g4/g6/
g7/g8_*_stats.csv schema (comparison, delta_pp, cohens_d, p) so this folds into
stats_unified_fdr.py the same way. The augmentation-vs-none tests themselves
already live in g8_resnet_se_augmentation_stats.py (unchanged, still valid) --
this script covers everything build ON TOP of the chandrop backbone:

SIAT (n=40, per-subject norm unless noted):
  1. ResNet-SE+CD vs base ResNet-SE (headline single-model comparison)
  2. ResNet-SE+CD vs SVM
  3. ResNet-SE+CD vs RF
  4. New best ensemble (SVM+RESNET_SE stacking, chandrop) vs old best-ensemble
     reference (SVM+RF+RESNET_SE weighted_soft, base ResNet-SE, 0.815)
  5. ResNet-SE+CD per-subject vs Deep CORAL (CD backbone, global-norm base)
  6. ResNet-SE+CD per-subject vs AdaBN post (CD backbone)
  7. AdaBN post vs pre (CD backbone) -- AdaBN lift is real on the CD backbone

ENABL3S (n=10, external validation, CD backbone):
  8. ResNet-SE+CD per-subject vs global norm
  9. Best ensemble (chandrop) vs hard vote
 10. Best ensemble (chandrop) vs best single model (SVM)

Output: report_figs/new_experiments/g9_chandrop_stats.csv
"""
from pathlib import Path
import hashlib
import numpy as np, pandas as pd
from scipy.stats import wilcoxon, norm
from sklearn.metrics import f1_score

ROOT = Path(__file__).parent
OUT = ROOT / "report_figs" / "new_experiments"; OUT.mkdir(parents=True, exist_ok=True)
SIAT_SUBS = list(range(1, 41))
EXT_SUBS = [156, 185, 186, 188, 189, 190, 191, 192, 193, 194]


def d_paired(a, b):
    d = np.asarray(a, float) - np.asarray(b, float)
    return d.mean() / d.std(ddof=1)


def row(comparison, a, b):
    a, b = np.asarray(a, float), np.asarray(b, float)
    w, p = wilcoxon(a, b)
    return dict(comparison=comparison,
                delta_pp=round((a.mean() - b.mean()) * 100, 2),
                cohens_d=round(d_paired(a, b), 3),
                p=p)


def proba_f1_vec(proba_dir, tag, subs):
    out = []
    for s in subs:
        npz = np.load(proba_dir / f"{tag}_sub{s:02d}.npz") if isinstance(s, int) and s < 100 \
            else np.load(proba_dir / f"{tag}_sub{s}.npz")
        yt = npz["y_true"].astype(int)
        yp = npz["proba"].argmax(1)
        out.append(f1_score(yt, yp, average="macro", zero_division=0))
    return np.array(out)


rows = []

# ---------------- SIAT (n=40) ----------------
cd_persubj = pd.read_csv(ROOT / "results_cnn_aug_resnet_se_chandrop_proba" / "cnn_arch_subjectwise.csv") \
    .sort_values("subject")["f1_macro"].to_numpy(float)
base_persubj = pd.read_csv(ROOT / "results_cnn_aug_resnet_se_none" / "cnn_arch_subjectwise.csv") \
    .sort_values("subject")["f1_macro"].to_numpy(float)

svm_siat = proba_f1_vec(ROOT / "results_ensemble_v2" / "proba", "SVM", SIAT_SUBS)
rf_siat = proba_f1_vec(ROOT / "results_ensemble_v2" / "proba", "RF", SIAT_SUBS)

rows.append(row("ResNet-SE+CD vs base ResNet-SE (SIAT, per-subject norm)", cd_persubj, base_persubj))
rows.append(row("ResNet-SE+CD vs SVM (SIAT)", cd_persubj, svm_siat))
rows.append(row("ResNet-SE+CD vs RF (SIAT)", cd_persubj, rf_siat))

new_ens = pd.read_csv(ROOT / "results_ensemble_v2_chandrop" / "ensemble_v2_subjectwise.csv")["SVM+RESNET_SE [stacking]"].to_numpy(float)
old_ens_ref = pd.read_csv(ROOT / "results_ensemble_v2" / "ensemble_v2_subjectwise.csv")["SVM+RF+RESNET_SE [weighted_soft]"].to_numpy(float)
rows.append(row("New best ensemble (SVM+RESNET_SE [stacking], chandrop) vs old best-ensemble reference (0.815)",
                new_ens, old_ens_ref))

coral_cd = pd.read_csv(ROOT / "results_deep_coral_chandrop" / "deep_coral_subjectwise.csv").sort_values("subject")["f1_macro"].to_numpy(float)
rows.append(row("ResNet-SE+CD per-subject vs Deep CORAL (CD backbone, SIAT)", cd_persubj, coral_cd))

adabn_cd = pd.read_csv(ROOT / "results_adabn_chandrop" / "adabn_subjectwise.csv").sort_values("subject")
adabn_cd_post = adabn_cd["f1_macro"].to_numpy(float)
adabn_cd_pre = adabn_cd["f1_pre_adabn"].to_numpy(float)
rows.append(row("ResNet-SE+CD per-subject vs AdaBN post (CD backbone, SIAT)", cd_persubj, adabn_cd_post))
rows.append(row("AdaBN post vs pre (CD backbone, SIAT)", adabn_cd_post, adabn_cd_pre))

# ---------------- ENABL3S (n=10) ----------------
ext_persubj = pd.read_csv(ROOT / "results_ext_chandrop_resnet_se_persubj" / "cnn_arch_subjectwise.csv") \
    .sort_values("subject")["f1_macro"].to_numpy(float)
ext_global = pd.read_csv(ROOT / "results_ext_chandrop_resnet_se_global" / "cnn_arch_subjectwise.csv") \
    .sort_values("subject")["f1_macro"].to_numpy(float)
rows.append(row("ResNet-SE+CD ENABL3S per-subject vs global norm", ext_persubj, ext_global))

ext_ens = pd.read_csv(ROOT / "results_ext_ensemble_v2_chandrop" / "ensemble_v2_subjectwise.csv")
ext_ens_soft = ext_ens["SVM+RESNET_SE [soft]"].to_numpy(float)
ext_ens_hard = ext_ens["SVM+RF+RESNET_SE [hard]"].to_numpy(float)
rows.append(row("Best ensemble (SVM+RESNET_SE [soft], chandrop, ENABL3S) vs hard vote", ext_ens_soft, ext_ens_hard))

svm_ext = proba_f1_vec(ROOT / "results_ext_ensemble_v2_chandrop" / "proba", "SVM", EXT_SUBS)
rows.append(row("Best ensemble (SVM+RESNET_SE [soft], chandrop, ENABL3S) vs best single model SVM", ext_ens_soft, svm_ext))

df = pd.DataFrame(rows)
df.to_csv(OUT / "g9_chandrop_stats.csv", index=False)
print(df.to_string(index=False))
print("\nwrote", OUT / "g9_chandrop_stats.csv")
