# -*- coding: utf-8 -*-
"""Whole-thesis Benjamini-Hochberg family, v4 (5 September 2026).

v3 rebuilt the family to 172 tests. v4 adds the paired tests generated by the
channel-dropout parity programme (P-1, P-2, P-3, P-5, P-6 extension, P-7) and by the
ENABL3S movement-blocked subject-dependent arm, all of which the writing phase wrote
into the thesis. Every p-value is read from its source outcome file; BH is recomputed
over the union, never patched.

Scope rule, unchanged: a test enters the family when the thesis reports the claim it
backs. P-6's core C1/C2 contrasts and P-8's correlations are therefore excluded, the
first because the thesis reports the extension rather than the core arms, the second
because they are Spearman-with-permutation tests and not paired Wilcoxon.
"""
import os, json, glob, subprocess, sys
import numpy as np, pandas as pd

CODE = os.path.join(os.environ["HOME"], "mnt", "FInal Project", "06_Code")
OUT  = os.path.join(CODE, "report_figs", "new_experiments")

# --- rebuild the v3 union by executing v3's construction, then extend -------------
src = open(os.path.join(CODE, "recompute_unified_fdr_v3.py"), encoding="utf-8").read()
head = src.split("df = pd.DataFrame(rows)")[0]
ns = {"__name__": "_v3"}
exec(compile(head, "v3_head", "exec"), ns)
rows, add = ns["rows"], ns["add"]
n_v3 = len(rows)

J = lambda *p: json.load(open(os.path.join(CODE, *p)))

# ---- P-1 occlusion cost falls with dose (4.8.2)
p1 = J("results_parity", "p1_outcome.json")
for a in p1["p1a"]["adjacent"]:
    add("mechanism", "P-1 occlusion vs dose (4.8.2)",
        "P-1 adjacent occlusion %s" % a["contrast"],
        a["p_raw"])
# ---- P-2 rank agreement, reported in 5.13 as a failed measure
p2 = J("results_parity", "p2_outcome.json")
add("mechanism", "P-2 rank agreement (5.13)",
    "P-2 per-subject rank consistency, CD vs baseline", p2["paired_wilcoxon"]["p_raw"])
# ---- P-3 external replication of channel dropout (4.12)
p3 = J("results_parity", "p3_outcome.json")
add("external", "P-3 external channel dropout (4.12)",
    "P-3 external CD vs no aug, per-subject norm", p3["primary"]["p_raw"])
add("external", "P-3 external channel dropout (4.12)",
    "P-3 external CD vs no aug, global norm", p3["secondary"]["p_raw"])
# ---- P-5 published alternative (4.8.2)
p5 = J("results_parity", "p5_outcome.json")
add("mechanism", "P-5 subset training (4.8.2)",
    "P-5 subset vs channel dropout", p5["primary"]["p_raw"])
add("mechanism", "P-5 subset training (4.8.2)",
    "P-5 subset vs no augmentation", p5["secondary"]["p_raw"])
# ---- P-6 extension, matched-variance gain jitter on the model of record (5.13)
p6 = J("results_parity", "p6_extension_outcome.json")
for m in p6["matched_points"]:
    add("mechanism", "P-6 extension matched variance (5.13)",
        "P-6 gain jitter vs channel dropout at SD %.2f" % m["sd"], m["p_raw"])
# ---- P-7 high-dose decomposition (4.8.2)
p7 = J("results_parity", "p7_outcome.json")
for k in ("D1", "D2"):
    add("mechanism", "P-7 high-dose decomposition (4.8.2)",
        "P-7 %s" % p7["sd50"][k]["label"], p7["sd50"][k]["p_raw"])
# ---- B8 extension: ENABL3S subject-dependent, movement-blocked (4.12)
b8e = pd.read_csv(os.path.join(CODE, "results_b8_ext", "b8_ext_freq56_w250_compare.csv"))
for _, r in b8e.iterrows():
    add("audit", "B8 ENABL3S subject-dependent split (4.12)",
        "B8ext pooled vs blocked SD F1 [%s] ENABL3S" % r["model"], r["wilcoxon_p"])

df = pd.DataFrame(rows)
print("v3 rows: %d   v4 additions: %d   total: %d" % (n_v3, len(df) - n_v3, len(df)))
dups = df.comparison[df.comparison.duplicated()].tolist()
assert not dups, dups

def bh(p):
    p = np.asarray(p, float); m = len(p); out = np.empty(m); prev = 1.0
    for rank, i in enumerate(np.argsort(p)[::-1]):
        prev = min(prev, p[i] * m / (m - rank)); out[i] = prev
    return out
def holm(p):
    p = np.asarray(p, float); m = len(p); out = np.empty(m); run = 0.0
    for rank, i in enumerate(np.argsort(p)):
        run = max(run, min(1.0, (m - rank) * p[i])); out[i] = run
    return out

prev = pd.read_csv(os.path.join(OUT, "unified_fdr_family_v3_A_all_reported.csv"))
prev["sig_old"] = prev.p_BH < 0.05
print("previous family (v3 scope A): m = %d, survivors = %d" % (len(prev), int(prev.sig_old.sum())))

for name, mask in (("A_all_reported", df.reported), ("B_bearing", df.bears)):
    sub = df[mask].reset_index(drop=True).copy()
    sub["p_BH"] = bh(sub.p); sub["p_holm"] = holm(sub.p); sub["sig"] = sub.p_BH < 0.05
    sub.to_csv(os.path.join(OUT, "unified_fdr_family_v4_%s.csv" % name), index=False)
    print("\n=== SCOPE %s: m = %d, survive BH = %d, fail = %d"
          % (name, len(sub), int(sub.sig.sum()), int((~sub.sig).sum())))
    newsig = dict(zip(sub.comparison, sub.sig))
    fell = [(r["comparison"], r["p_BH"]) for _, r in prev.iterrows()
            if r["sig_old"] and r["comparison"] in newsig and not newsig[r["comparison"]]]
    rose = [(r["comparison"], r["p_BH"]) for _, r in prev.iterrows()
            if (not r["sig_old"]) and r["comparison"] in newsig and newsig[r["comparison"]]]
    print("  previously surviving that now FAIL: %d" % len(fell))
    for c, pb in fell: print("     FELL %-78s oldBH=%.4f" % (c[:78], pb))
    print("  previously failing that now SURVIVE: %d" % len(rose))
    for c, pb in rose: print("     ROSE %-78s oldBH=%.4f" % (c[:78], pb))
    edge = sub[(sub.p_BH > 0.030) & (sub.p_BH < 0.080)].sort_values("p_BH")
    print("  within BH 0.030-0.080: %d" % len(edge))
    for _, r in edge.iterrows():
        print("     EDGE %-72s BH=%.4f %s" % (str(r["comparison"])[:72], r["p_BH"],
                                              "sig" if r["sig"] else "NS"))
    if name == "A_all_reported":
        newrows = sub[sub.comparison.str.startswith(("P-1 ","P-2 ","P-3 ","P-5 ","P-6 ","P-7 ","B8ext"))]
        print("\n  the %d new tests:" % len(newrows))
        for _, r in newrows.sort_values("p").iterrows():
            print("     %-70s raw=%.3g BH=%.4f %s" % (str(r["comparison"])[:70], r["p"], r["p_BH"],
                                                      "sig" if r["sig"] else "NS"))
