# -*- coding: utf-8 -*-
"""Whole-thesis Benjamini-Hochberg family, v3 (4 September 2026).

Rebuilds the family from RAW p-values: the 145 rows settled on 2 September plus every
paired test generated by the September audit and mechanism queue. BH is recomputed over
the union, never patched.
"""
import os, json, glob
import numpy as np, pandas as pd

CODE = os.path.join(os.environ["HOME"], "mnt", "FInal Project", "06_Code")
OUT  = os.path.join(CODE, "report_figs", "new_experiments")

base = pd.read_csv(os.path.join(OUT, "unified_fdr_family_145.csv"))
assert len(base) == 145, len(base)
rows = [dict(group=r["group"], family=r["family"], comparison=r["comparison"],
             p=float(r["p"]), reported=bool(r["reported"]), bears=bool(r["bears"]))
        for _, r in base.iterrows()]
n0 = len(rows)

def add(group, family, comparison, p, reported=True, bears=True):
    rows.append(dict(group=group, family=family, comparison=comparison,
                     p=float(p), reported=reported, bears=bears))

# ---- W-5 depth vs capacity (4.8.1). Only the two interaction tests are novel;
# the three "gain" rows re-measure the channel-dropout gain already in the family.
w5 = pd.read_csv(os.path.join(CODE, "results_w5", "w5_depth_capacity_tests.csv"))
W5_DUP = {"BASE gain (chandrop - noaug)", "SHALLOW-MATCHED gain", "NARROW-MATCHED gain"}
for _, r in w5.iterrows():
    if r["comparison"] in W5_DUP: continue
    add("mechanism", "W-5 depth vs capacity (4.8.1)", "W-5 " + r["comparison"], r["p_raw"])

# ---- P-9 backbone split (4.8.2)
p9 = json.load(open(os.path.join(CODE, "results_locus", "p9_outcome.json")))
add("mechanism", "P-9 backbone split (4.8.2)",
    "P-9 occlusion reduction, resnet_se vs SE-free (paired)",
    p9["paired_backbone_reduction_diff_pp"]["p_raw"])

# ---- P-10 mean-preserving dose sweep (4.8.2). Four unique contrasts; the
# post-peak SD 0.60 row is the same test as adjacent 0.50-0.60, so it is not double counted.
p10 = json.load(open(os.path.join(CODE, "results_locus", "p10_outcome.json")))
for a in p10["adjacent_contrasts"]:
    if (a["lo_sd"], a["hi_sd"]) in [(0.4, 0.5), (0.5, 0.6)]:
        add("mechanism", "P-10 dose sweep (4.8.2)",
            "P-10 adjacent SD %.2f vs %.2f" % (a["lo_sd"], a["hi_sd"]), a["p_raw"])
for c in p10["post_peak_contrasts"]:
    if c["sd"] in (0.8, 1.0):
        add("mechanism", "P-10 dose sweep (4.8.2)",
            "P-10 peak vs SD %.2f" % c["sd"], c["p_raw"])

# ---- B3 per-subject silhouette (4.13.2)
b3 = json.load(open(os.path.join(CODE, "results_locus", "b3_outcome.json")))
b3s = json.dumps(b3)
add("audit", "B3 per-subject silhouette (4.13.2)",
    "B3 silhouette rung3 vs rung4 (paired)", 1.819e-12)
add("audit", "B3 per-subject silhouette (4.13.2)",
    "B3 silhouette rung3 vs rung0 (paired)", 9.597e-06)
add("audit", "B3 per-subject silhouette (4.13.2)",
    "B3 within-subject silhouette-F1 Spearman vs 0", 1.254e-06)

# ---- B8 subject-dependent split (4.1.3): every config x model
nb8 = 0
for f in sorted(glob.glob(os.path.join(CODE, "results_b8_sd", "b8_*_outcome.json"))):
    if f.endswith("b8_outcome.json"): continue
    d = json.load(open(f))
    if "rows" in d:
        for r in d["rows"]:
            add("audit", "B8 subject-dependent split (4.1.3)",
                "B8 pooled vs blocked SD F1 [%s] %s" % (r["model"], r["tag"]), r["wilcoxon_p"])
            nb8 += 1
    elif "wilcoxon_p" in d:
        add("audit", "B8 subject-dependent split (4.1.3)",
            "B8 pooled vs blocked SD F1 [CNN] %s" % d["tag"], d["wilcoxon_p"]); nb8 += 1

# ---- S-1 active-only STDUP (4.3.1)
s1 = json.load(open(os.path.join(CODE, "results_locus", "s1_outcome.json")))
for r in s1["normalization_delta"]:
    add("audit", "S-1 active-only STDUP (4.3.1)",
        "S-1 per-subject vs global, active-only [%s]" % r["model"], r["wilcoxon_p"])

df = pd.DataFrame(rows)
print("base rows: %d   new rows: %d   total: %d   (B8 contributed %d)"
      % (n0, len(df) - n0, len(df), nb8))
assert df.comparison.duplicated().sum() == 0, df.comparison[df.comparison.duplicated()].tolist()

def bh(p):
    p = np.asarray(p, float); m = len(p); out = np.empty(m); prev = 1.0
    for rank, i in enumerate(np.argsort(p)[::-1]):
        prev = min(prev, p[i] * m / (m - rank)); out[i] = prev
    return out
def holm(p):
    p = np.asarray(p, float); m = len(p); out = np.empty(m); run = 0.0
    for rank, i in enumerate(np.argsort(p)):
        run = max(run, min(1.0, (m - rank) * p[i])); out[i] = run
    return out

old = base.copy(); old["sig_old"] = old.p_BH < 0.05
print("previous family: m = 145, survivors = %d" % int(old.sig_old.sum()))

for name, mask in (("A_all_reported", df.reported), ("B_bearing", df.bears)):
    sub = df[mask].reset_index(drop=True).copy()
    sub["p_BH"] = bh(sub.p); sub["p_holm"] = holm(sub.p); sub["sig"] = sub.p_BH < 0.05
    sub.to_csv(os.path.join(OUT, "unified_fdr_family_v3_%s.csv" % name), index=False)
    print("\n=== SCOPE %s: m = %d, survive BH = %d, fail = %d"
          % (name, len(sub), int(sub.sig.sum()), int((~sub.sig).sum())))
    newsig = dict(zip(sub.comparison, sub.sig))
    fell = [(r["comparison"], r["p_BH"]) for _, r in old.iterrows()
            if r["sig_old"] and r["comparison"] in newsig and not newsig[r["comparison"]]]
    rose = [(r["comparison"], r["p_BH"]) for _, r in old.iterrows()
            if (not r["sig_old"]) and r["comparison"] in newsig and newsig[r["comparison"]]]
    print("  previously surviving that now FAIL: %d" % len(fell))
    for c, pb in fell: print("     FELL %-80s oldBH=%.4f" % (c[:80], pb))
    print("  previously failing that now SURVIVE: %d" % len(rose))
    for c, pb in rose: print("     ROSE %-80s oldBH=%.4f" % (c[:80], pb))
    edge = sub[(sub.p_BH > 0.030) & (sub.p_BH < 0.080)].sort_values("p_BH")
    print("  within BH 0.030-0.080: %d" % len(edge))
    for _, r in edge.iterrows():
        print("     EDGE %-74s BH=%.4f %s" % (str(r["comparison"])[:74], r["p_BH"],
                                              "sig" if r["sig"] else "NS"))
